name: Deploy

on:
  push:
    branches: [github-action]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # aa
      - name: git clone
        uses: actions/checkout@v2

      - name: yarn install
        run: yarn install

      - name: build
        run: npm run build

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            out s3://ctrlf.space
